xandzia: add task_11
kottans-frontend-2018/assignments_xandzia pull request #1
Opened 2018-01-25 11:59 UTC by xandzia

test pull request

task_11

- [demo](https://xandzia.github.io/kottans_frontend/task_11/index.html)

- [repo](https://github.com/xandzia/kottans_frontend/tree/master/task_11)

2018-01-25 13:04 UTC, viktor-yakubiv requested changes
You must not commit generated files, like cache ones, to the repository.

Please, review your global `.gitignore` or add local one.

---

Do not commit unnecessary files. It harms people who read your code. Just find the file, see it's empty and probably is not used and wondering, why is it here?

2018-01-25 13:14 UTC, viktor-yakubiv commented
Also, pay attention to indentation and line limitations up 80, 100 or 120 characters long. Follow clear convention of code writing.

2018-01-25 13:24 UTC, viktor-yakubiv commented
If you use a tool, e.g. SASS, use it wisely.

In this case, do not create a mess in the repository. Now you have `styles.scss` in the root, which contains css-reset, three files in the `sass` directory: two are empty, one contains reset too. But you could have one clean directory with sass-modules, actually well-named files.

Think about [project structure](http://thesassway.com/beginner/how-to-structure-a-sass-project).

2018-01-25 13:32 UTC, viktor-yakubiv commented
All active element __must__ respond to user interaction. It means, any button, link, radio or checkbox must have hover and focus styles.

2018-01-25 13:33 UTC, viktor-yakubiv requested changes
All active element must respond to user interaction. It means, any button, link, radio or checkbox must have hover and focus styles.

2018-01-25 13:33 UTC, viktor-yakubiv commented on task_11/index.html
> +    <!--    Define keywords for search engines:-->
Code must be self-documented as much as possible.

Highly suggest you avoid stupid comments for lines which are clear without it.

2018-01-25 16:33 UTC, viktor-yakubiv approved these changes

2018-01-25 16:34 UTC, viktor-yakubiv commented
It's much better! Good job!

2018-01-25 16:37 UTC, viktor-yakubiv commented
You just deleted too many files, but it's okay. You may leave only one pretty file with styles.

2018-01-25 16:38 UTC, viktor-yakubiv commented
@AMashoshyna, are you able to review?

2018-01-30 13:06 UTC, feroxes approved these changes

2018-02-01 13:14 UTC, merged